### ISSUE TITLE
(reference to original) FireORM official roadmap

### ISSUE THREAD

**Issue by elersong** [elersong/fireorm24#7]
Collaborations are welcome! If you want to start working on a feature that is listed below, please create another issue to start the discussion. This issue is only meant to be used as a placeholder.

### v1 roadmap

- [x] Improvements in api documentation https://github.com/wovalle/fireorm/issues/78
- [ ]  Support for methods (and getters/setters) in models
 - [x] Integration tests with real firestore db https://github.com/wovalle/fireorm/issues/31
 - [ ] Transactions support
 - [x] OrderBy https://github.com/wovalle/fireorm/issues/30
 - [x] Limit https://github.com/wovalle/fireorm/issues/18
 - [ ] Stricter typescript rules
 - [ ] Better error handling (and custom errors)
 - [x] Lazy subcollections (initialize subcollections without having to query the parent collection first) https://github.com/wovalle/fireorm/issues/51
 - [ ] Collection Group Queries

### Next major
 - [ ] Pagination
 - [ ] Firestore events subscription/dispatching support
 - [ ] Relationships (1:1, 1:n, n:n, eager, lazy) https://github.com/wovalle/fireorm/issues/32
 - [ ] Firebase js client support (probably)
 - [ ] Increase the compatibility with Raw Firestore Documents

### Wishlist
 - [ ] Javascript support
 - [ ] Browser support
 - [ ] Firebase Realtime database support
 - [ ] Investigate if models can be enforced with db rules (cli project)
 - [ ] (cli) Migrations
 - [ ] Change tracking (instead of updating the entire document, just update the keys that changed)
 - [ ] Custom decorators like @createdOnField, @updatedOnField
 - [ ] Custom hooks? onCreate, onUpdate, onDelete, onRead
 - [ ] (cli) Indexes management: throw custom errors when trying to do range filters for non-indexes for non indexed fields, creation and deletion of indexes.
